apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification-container
          image: redis:6.2.6  # Changed from nginx:latest to redis:6.2.6
          ports:
            - containerPort: 6379  # Redis uses port 6379
